# Generated by Django 2.2.5 on 2019-09-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='headshots/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='headshots/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('date_1', models.DateField(blank=True, null=True)),
                ('date_2', models.DateField(blank=True, null=True)),
                ('date_3', models.DateField(blank=True, null=True)),
                ('date_4', models.DateField(blank=True, null=True)),
                ('date_5', models.DateField(blank=True, null=True)),
                ('date_6', models.DateField(blank=True, null=True)),
                ('date_7', models.DateField(blank=True, null=True)),
                ('date_8', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govlink.Category')),
            ],
        ),
    ]
