# Generated by Django 2.2.5 on 2019-09-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govlink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
